variable = 4
print(type(variable))
variable = float(variable)
print(type(variable))
variable = bool(variable)
print(type(variable))
variable = str(variable)
print(type(variable))
variable = list(variable)
print(type(variable))
